services:
  - type: web
    name: smart-waste-inspector
    env: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
