services:
  - type: web
    name: smart-waste-inspector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    runtime: python
    region: oregon  # or keep default
    plan: free
