services:
  - type: web
    name: smart-waste-inspector
    env: python
    runtime: python
    buildCommand: |
      pyenv install 3.10.13
      pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
