services:
  - type: web
    name: smart-waste-inspector
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
